/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chessoracle;

import javax.swing.ImageIcon;

/**
 *
 * @author alexy
 */
public class ChessOracle extends javax.swing.JFrame {

    /**
     * Creates new form ChessOracle
     */
    public ChessOracle() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        A8 = new javax.swing.JButton();
        B8 = new javax.swing.JButton();
        C8 = new javax.swing.JButton();
        D8 = new javax.swing.JButton();
        E8 = new javax.swing.JButton();
        F8 = new javax.swing.JButton();
        G8 = new javax.swing.JButton();
        H8 = new javax.swing.JButton();
        B7 = new javax.swing.JButton();
        C7 = new javax.swing.JButton();
        D7 = new javax.swing.JButton();
        E7 = new javax.swing.JButton();
        F7 = new javax.swing.JButton();
        A7 = new javax.swing.JButton();
        G7 = new javax.swing.JButton();
        H7 = new javax.swing.JButton();
        B6 = new javax.swing.JButton();
        C6 = new javax.swing.JButton();
        D6 = new javax.swing.JButton();
        E6 = new javax.swing.JButton();
        F6 = new javax.swing.JButton();
        A6 = new javax.swing.JButton();
        G6 = new javax.swing.JButton();
        H6 = new javax.swing.JButton();
        B5 = new javax.swing.JButton();
        C5 = new javax.swing.JButton();
        D5 = new javax.swing.JButton();
        E5 = new javax.swing.JButton();
        F5 = new javax.swing.JButton();
        A5 = new javax.swing.JButton();
        G5 = new javax.swing.JButton();
        H5 = new javax.swing.JButton();
        D4 = new javax.swing.JButton();
        G4 = new javax.swing.JButton();
        E4 = new javax.swing.JButton();
        H4 = new javax.swing.JButton();
        B4 = new javax.swing.JButton();
        A4 = new javax.swing.JButton();
        F4 = new javax.swing.JButton();
        C4 = new javax.swing.JButton();
        D3 = new javax.swing.JButton();
        G3 = new javax.swing.JButton();
        E3 = new javax.swing.JButton();
        H3 = new javax.swing.JButton();
        B3 = new javax.swing.JButton();
        A3 = new javax.swing.JButton();
        F3 = new javax.swing.JButton();
        C3 = new javax.swing.JButton();
        D2 = new javax.swing.JButton();
        G2 = new javax.swing.JButton();
        E2 = new javax.swing.JButton();
        H2 = new javax.swing.JButton();
        B2 = new javax.swing.JButton();
        A2 = new javax.swing.JButton();
        F2 = new javax.swing.JButton();
        C2 = new javax.swing.JButton();
        D1 = new javax.swing.JButton();
        G1 = new javax.swing.JButton();
        E1 = new javax.swing.JButton();
        H1 = new javax.swing.JButton();
        B1 = new javax.swing.JButton();
        A1 = new javax.swing.JButton();
        F1 = new javax.swing.JButton();
        C1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CHESS ORACLE ©");
        setResizable(false);

        A8.setBackground(new java.awt.Color(121, 60, 26));
        A8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A8MouseClicked(evt);
            }
        });

        B8.setBackground(new java.awt.Color(187, 142, 69));
        B8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B8MouseClicked(evt);
            }
        });

        C8.setBackground(new java.awt.Color(121, 60, 26));
        C8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                C8MouseClicked(evt);
            }
        });

        D8.setBackground(new java.awt.Color(187, 142, 69));
        D8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                D8MouseClicked(evt);
            }
        });

        E8.setBackground(new java.awt.Color(121, 60, 26));
        E8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                E8MouseClicked(evt);
            }
        });

        F8.setBackground(new java.awt.Color(187, 142, 69));
        F8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F8MouseClicked(evt);
            }
        });

        G8.setBackground(new java.awt.Color(121, 60, 26));
        G8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                G8MouseClicked(evt);
            }
        });

        H8.setBackground(new java.awt.Color(187, 142, 69));
        H8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                H8MouseClicked(evt);
            }
        });

        B7.setBackground(new java.awt.Color(121, 60, 26));

        C7.setBackground(new java.awt.Color(187, 142, 69));

        D7.setBackground(new java.awt.Color(121, 60, 26));

        E7.setBackground(new java.awt.Color(187, 142, 69));

        F7.setBackground(new java.awt.Color(121, 60, 26));

        A7.setBackground(new java.awt.Color(187, 142, 69));

        G7.setBackground(new java.awt.Color(187, 142, 69));

        H7.setBackground(new java.awt.Color(121, 60, 26));

        B6.setBackground(new java.awt.Color(187, 142, 69));

        C6.setBackground(new java.awt.Color(121, 60, 26));

        D6.setBackground(new java.awt.Color(187, 142, 69));

        E6.setBackground(new java.awt.Color(121, 60, 26));

        F6.setBackground(new java.awt.Color(187, 142, 69));

        A6.setBackground(new java.awt.Color(121, 60, 26));

        G6.setBackground(new java.awt.Color(121, 60, 26));

        H6.setBackground(new java.awt.Color(187, 142, 69));

        B5.setBackground(new java.awt.Color(121, 60, 26));

        C5.setBackground(new java.awt.Color(187, 142, 69));

        D5.setBackground(new java.awt.Color(121, 60, 26));

        E5.setBackground(new java.awt.Color(187, 142, 69));

        F5.setBackground(new java.awt.Color(121, 60, 26));

        A5.setBackground(new java.awt.Color(187, 142, 69));

        G5.setBackground(new java.awt.Color(187, 142, 69));

        H5.setBackground(new java.awt.Color(121, 60, 26));

        D4.setBackground(new java.awt.Color(187, 142, 69));

        G4.setBackground(new java.awt.Color(121, 60, 26));

        E4.setBackground(new java.awt.Color(121, 60, 26));

        H4.setBackground(new java.awt.Color(187, 142, 69));

        B4.setBackground(new java.awt.Color(187, 142, 69));

        A4.setBackground(new java.awt.Color(121, 60, 26));

        F4.setBackground(new java.awt.Color(187, 142, 69));

        C4.setBackground(new java.awt.Color(121, 60, 26));

        D3.setBackground(new java.awt.Color(121, 60, 26));

        G3.setBackground(new java.awt.Color(187, 142, 69));

        E3.setBackground(new java.awt.Color(187, 142, 69));

        H3.setBackground(new java.awt.Color(121, 60, 26));

        B3.setBackground(new java.awt.Color(121, 60, 26));

        A3.setBackground(new java.awt.Color(187, 142, 69));

        F3.setBackground(new java.awt.Color(121, 60, 26));

        C3.setBackground(new java.awt.Color(187, 142, 69));

        D2.setBackground(new java.awt.Color(187, 142, 69));

        G2.setBackground(new java.awt.Color(121, 60, 26));

        E2.setBackground(new java.awt.Color(121, 60, 26));

        H2.setBackground(new java.awt.Color(187, 142, 69));

        B2.setBackground(new java.awt.Color(187, 142, 69));

        A2.setBackground(new java.awt.Color(121, 60, 26));

        F2.setBackground(new java.awt.Color(187, 142, 69));

        C2.setBackground(new java.awt.Color(121, 60, 26));

        D1.setBackground(new java.awt.Color(121, 60, 26));

        G1.setBackground(new java.awt.Color(187, 142, 69));

        E1.setBackground(new java.awt.Color(187, 142, 69));

        H1.setBackground(new java.awt.Color(121, 60, 26));

        B1.setBackground(new java.awt.Color(121, 60, 26));

        A1.setBackground(new java.awt.Color(187, 142, 69));

        F1.setBackground(new java.awt.Color(121, 60, 26));

        C1.setBackground(new java.awt.Color(187, 142, 69));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(128, 76, 19));
        jLabel1.setText("8");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(128, 76, 19));
        jLabel2.setText("7");

        jLabel3.setFont(new java.awt.Font("Ubuntu", 3, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(128, 76, 19));
        jLabel3.setText("6");

        jLabel4.setFont(new java.awt.Font("Ubuntu", 3, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(128, 76, 19));
        jLabel4.setText("5");

        jLabel5.setFont(new java.awt.Font("Ubuntu", 3, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(128, 76, 19));
        jLabel5.setText("4");

        jLabel6.setFont(new java.awt.Font("Ubuntu", 3, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(128, 76, 19));
        jLabel6.setText("3");

        jLabel7.setFont(new java.awt.Font("Ubuntu", 3, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(128, 76, 19));
        jLabel7.setText("1");

        jLabel8.setFont(new java.awt.Font("Ubuntu", 3, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(128, 76, 19));
        jLabel8.setText("2");

        jLabel9.setFont(new java.awt.Font("Ubuntu", 3, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(128, 76, 19));
        jLabel9.setText("A");

        jLabel10.setFont(new java.awt.Font("Ubuntu", 3, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(128, 76, 19));
        jLabel10.setText("C");

        jLabel11.setFont(new java.awt.Font("Ubuntu", 3, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(128, 76, 19));
        jLabel11.setText("B");

        jLabel12.setFont(new java.awt.Font("Ubuntu", 3, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(128, 76, 19));
        jLabel12.setText("D");

        jLabel13.setFont(new java.awt.Font("Ubuntu", 3, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(128, 76, 19));
        jLabel13.setText("F");

        jLabel14.setFont(new java.awt.Font("Ubuntu", 3, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(128, 76, 19));
        jLabel14.setText("E");

        jLabel15.setFont(new java.awt.Font("Ubuntu", 3, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(128, 76, 19));
        jLabel15.setText("H");

        jLabel16.setFont(new java.awt.Font("Ubuntu", 3, 36)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(128, 76, 19));
        jLabel16.setText("G");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(A8, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B8, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(C8, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(D8, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(E8, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(F8, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(G8, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(H8, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(A7, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B7, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(C7, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(D7, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(E7, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(F7, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(G7, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(H7, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(A6, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B6, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(C6, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(D6, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(E6, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(F6, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(G6, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(H6, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(A5, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B5, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(C5, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(D5, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(E5, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(F5, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(G5, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(H5, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(A4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(C4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(D4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(E4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(F4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(G4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(H4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(A3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(C3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(D3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(E3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(F3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(G3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(H3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(A2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(C2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(D2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(E2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(F2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(G2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(H2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(A1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(C1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(D1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(E1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(F1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(G1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(H1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1)
                        .addGap(38, 38, 38)
                        .addComponent(jLabel2)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel3)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel4)
                        .addGap(39, 39, 39)
                        .addComponent(jLabel5)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel6)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel8)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(H8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(G8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(F8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(E8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(D8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(C8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(A8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(H7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(G7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(F7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(E7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(D7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(C7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(A7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(H6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(G6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(F6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(E6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(D6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(C6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(A6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(H5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(G5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(F5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(E5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(D5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(C5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(A5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(H4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(G4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(F4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(E4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(D4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(C4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(A4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(H3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(G3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(F3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(E3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(D3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(C3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(A3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(H2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(G2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(F2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(E2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(D2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(C2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(A2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(H1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(G1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(F1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(E1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(D1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(C1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(A1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void A8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A8MouseClicked
        // TODO add your handling code here:
        tablero[0][0]++;
        if (tablero[0][0] == 1) {
            if (Peon_b()) {
                A8.setIcon(new ImageIcon(this.getClass().getResource("PeonBlanco.svg.png")));
                tablero[0][0]++;
            }else if (!Caballo_b() && !Caballo_n()) {
                tablero[0][0] += 2;
                A8.setIcon(new ImageIcon(this.getClass().getResource("ReyBlanco.svg.png")));
            } 
        } else if (tablero[0][0] == 3) {
            tablero[0][0]=0;
            if (Caballo_b()) {
                A8.setIcon(new ImageIcon(this.getClass().getResource("CaballoBlanco.svg.png")));
                tablero[0][0]=3;
            } else if (Caballo_n()) {
                tablero[0][0]++;
                A8.setIcon(new ImageIcon(this.getClass().getResource("CaballoNegro.svg.png")));
                if(!Caballo_b()){
                    tablero[0][0]+=3;
                }
            }
            else if(!Caballo_n() && !Caballo_b()){
                tablero[0][0]+=5;
                A8.setIcon(new ImageIcon(this.getClass().getResource("ReyBlanco.svg.png")));
            }
        } else if (tablero[0][0] == 4) {
            tablero[0][0]=0;
            if (Caballo_n()) {
                A8.setIcon(new ImageIcon(this.getClass().getResource("CaballoNegro.svg.png")));
                tablero[0][0]+=4;
            }else{
                tablero[0][0]+=5;
                A8.setIcon(new ImageIcon(this.getClass().getResource("ReyBlanco.svg.png")));
            }
        } else if (tablero[0][0] == 5) {
            A8.setIcon(new ImageIcon(this.getClass().getResource("ReyBlanco.svg.png")));
        } else if (tablero[0][0] == 6) {
            A8.setIcon(new ImageIcon(this.getClass().getResource("ReyNegro.svg.png")));
        } else {
            A8.setIcon(null);
            tablero[0][0] = 0;
        }
        impr();
    }//GEN-LAST:event_A8MouseClicked

    private void B8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B8MouseClicked
        // TODO add your handling code here:
        tablero[0][1]++;
        if (tablero[0][1] == 1) {
            if (Peon_b()) {
                B8.setIcon(new ImageIcon(this.getClass().getResource("PeonBlanco.svg.png")));
                tablero[0][1]++;
            }else if (!Caballo_b() && !Caballo_n()) {
                tablero[0][1] += 2;
                B8.setIcon(new ImageIcon(this.getClass().getResource("ReyBlanco.svg.png")));
            } 
        } else if (tablero[0][1] == 3) {
            tablero[0][1]=0;
            if (Caballo_b()) {
                B8.setIcon(new ImageIcon(this.getClass().getResource("CaballoBlanco.svg.png")));
                tablero[0][1]=3;
            } else if (Caballo_n()) {
                tablero[0][1]++;
                B8.setIcon(new ImageIcon(this.getClass().getResource("CaballoNegro.svg.png")));
                if(!Caballo_b()){
                    tablero[0][1]+=3;
                }
            }else if(!Caballo_n() && !Caballo_b()){
                tablero[0][1]+=5;
                B8.setIcon(new ImageIcon(this.getClass().getResource("ReyBlanco.svg.png")));
            }
        } else if (tablero[0][1] == 4) {
            tablero[0][1]=0;
            if (Caballo_n()) {
                B8.setIcon(new ImageIcon(this.getClass().getResource("CaballoNegro.svg.png")));
                tablero[0][1]+=4;
            }else{
                tablero[0][1]+=5;
                B8.setIcon(new ImageIcon(this.getClass().getResource("ReyBlanco.svg.png")));
            }
        } else if (tablero[0][1] == 5) {
            B8.setIcon(new ImageIcon(this.getClass().getResource("ReyBlanco.svg.png")));
        } else if (tablero[0][1] == 6) {
            B8.setIcon(new ImageIcon(this.getClass().getResource("ReyNegro.svg.png")));
        } else {
            B8.setIcon(null);
            tablero[0][1] = 0;
        }
        impr();
    }//GEN-LAST:event_B8MouseClicked

    private void C8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C8MouseClicked
        // TODO add your handling code here:
        tablero[0][2]++;
        if (tablero[0][2] == 1) {
            if (Peon_b()) {
                C8.setIcon(new ImageIcon(this.getClass().getResource("PeonBlanco.svg.png")));
                tablero[0][2]++;
            }else if (!Caballo_b() && !Caballo_n()) {
                tablero[0][2] += 2;
                C8.setIcon(new ImageIcon(this.getClass().getResource("ReyBlanco.svg.png")));
            } 
        } else if (tablero[0][2] == 3) {
            tablero[0][2]=0;
            if (Caballo_b()) {
                C8.setIcon(new ImageIcon(this.getClass().getResource("CaballoBlanco.svg.png")));
                tablero[0][2]=3;
            } else if (Caballo_n()) {
                tablero[0][2]++;
                C8.setIcon(new ImageIcon(this.getClass().getResource("CaballoNegro.svg.png")));
                if(!Caballo_b()){
                    tablero[0][2]+=3;
                }
            }else if(!Caballo_n() && !Caballo_b()){
                tablero[0][2]+=5;
                C8.setIcon(new ImageIcon(this.getClass().getResource("ReyBlanco.svg.png")));
            }
        } else if (tablero[0][2] == 4) {
            tablero[0][2]=0;
            if (Caballo_n()) {
                C8.setIcon(new ImageIcon(this.getClass().getResource("CaballoNegro.svg.png")));
                tablero[0][2]+=4;
            }else{
                tablero[0][2]+=5;
                C8.setIcon(new ImageIcon(this.getClass().getResource("ReyBlanco.svg.png")));
            }
        } else if (tablero[0][2] == 5) {
            C8.setIcon(new ImageIcon(this.getClass().getResource("ReyBlanco.svg.png")));
        } else if (tablero[0][2] == 6) {
            C8.setIcon(new ImageIcon(this.getClass().getResource("ReyNegro.svg.png")));
        } else {
            C8.setIcon(null);
            tablero[0][2] = 0;
        }
        impr();
    }//GEN-LAST:event_C8MouseClicked

    private void D8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_D8MouseClicked
        // TODO add your handling code here:
        tablero[0][3]++;
        if (tablero[0][3] == 1) {
            if (Peon_b()) {
                D8.setIcon(new ImageIcon(this.getClass().getResource("PeonBlanco.svg.png")));
                tablero[0][3]++;
            }else if (!Caballo_b() && !Caballo_n()) {
                tablero[0][3] += 2;
                D8.setIcon(new ImageIcon(this.getClass().getResource("ReyBlanco.svg.png")));
            } 
        } else if (tablero[0][3] == 3) {
            tablero[0][3]=0;
            if (Caballo_b()) {
                D8.setIcon(new ImageIcon(this.getClass().getResource("CaballoBlanco.svg.png")));
                tablero[0][3]=3;
            } else if (Caballo_n()) {
                tablero[0][3]++;
                D8.setIcon(new ImageIcon(this.getClass().getResource("CaballoNegro.svg.png")));
                if(!Caballo_b()){
                    tablero[0][3]+=3;
                }
            }else if(!Caballo_n() && !Caballo_b()){
                tablero[0][3]+=5;
                D8.setIcon(new ImageIcon(this.getClass().getResource("ReyBlanco.svg.png")));
            }
        } else if (tablero[0][3] == 4) {
            tablero[0][3]=0;
            if (Caballo_n()) {
                D8.setIcon(new ImageIcon(this.getClass().getResource("CaballoNegro.svg.png")));
                tablero[0][3]+=4;
            }else{
                tablero[0][3]+=5;
                D8.setIcon(new ImageIcon(this.getClass().getResource("ReyBlanco.svg.png")));
            }
        } else if (tablero[0][3] == 5) {
            D8.setIcon(new ImageIcon(this.getClass().getResource("ReyBlanco.svg.png")));
        } else if (tablero[0][3] == 6) {
            D8.setIcon(new ImageIcon(this.getClass().getResource("ReyNegro.svg.png")));
        } else {
            D8.setIcon(null);
            tablero[0][3] = 0;
        }
        impr();
    }//GEN-LAST:event_D8MouseClicked

    private void E8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_E8MouseClicked
        // TODO add your handling code here:
        tablero[0][4]++;
        if (tablero[0][4] == 1) {
            if (Peon_b()) {
                E8.setIcon(new ImageIcon(this.getClass().getResource("PeonBlanco.svg.png")));
                tablero[0][4]++;
            }else if (!Caballo_b() && !Caballo_n()) {
                tablero[0][4] += 2;
                E8.setIcon(new ImageIcon(this.getClass().getResource("ReyBlanco.svg.png")));
            } 
        } else if (tablero[0][4] == 3) {
            tablero[0][4]=0;
            if (Caballo_b()) {
                E8.setIcon(new ImageIcon(this.getClass().getResource("CaballoBlanco.svg.png")));
                tablero[0][4]=3;
            } else if (Caballo_n()) {
                tablero[0][4]++;
                E8.setIcon(new ImageIcon(this.getClass().getResource("CaballoNegro.svg.png")));
                if(!Caballo_b()){
                    tablero[0][4]+=3;
                }
            }else if(!Caballo_n() && !Caballo_b()){
                tablero[0][4]+=5;
                E8.setIcon(new ImageIcon(this.getClass().getResource("ReyBlanco.svg.png")));
            }
        } else if (tablero[0][4] == 4) {
            tablero[0][4]=0;
            if (Caballo_n()) {
                E8.setIcon(new ImageIcon(this.getClass().getResource("CaballoNegro.svg.png")));
                tablero[0][4]+=4;
            }else{
                tablero[0][4]+=5;
                E8.setIcon(new ImageIcon(this.getClass().getResource("ReyBlanco.svg.png")));
            }
        } else if (tablero[0][4] == 5) {
            E8.setIcon(new ImageIcon(this.getClass().getResource("ReyBlanco.svg.png")));
        } else if (tablero[0][4] == 6) {
            E8.setIcon(new ImageIcon(this.getClass().getResource("ReyNegro.svg.png")));
        } else {
            E8.setIcon(null);
            tablero[0][4] = 0;
        }
        impr();
    }//GEN-LAST:event_E8MouseClicked

    private void F8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_F8MouseClicked
        // TODO add your handling code here:
        tablero[0][5]++;
        if (tablero[0][5] == 1) {
            if (Peon_b()) {
                F8.setIcon(new ImageIcon(this.getClass().getResource("PeonBlanco.svg.png")));
                tablero[0][5]++;
            }else if (!Caballo_b() && !Caballo_n()) {
                tablero[0][5] += 2;
                F8.setIcon(new ImageIcon(this.getClass().getResource("ReyBlanco.svg.png")));
            } 
        }else if (tablero[0][5] == 3) {
            tablero[0][5]=0;
            if (Caballo_b()) {
                F8.setIcon(new ImageIcon(this.getClass().getResource("CaballoBlanco.svg.png")));
                tablero[0][5]=3;
            } else if (Caballo_n()) {
                tablero[0][5]++;
                F8.setIcon(new ImageIcon(this.getClass().getResource("CaballoNegro.svg.png")));
                if(!Caballo_b()){
                    tablero[0][5]+=3;
                }
            }else if(!Caballo_n() && !Caballo_b()){
                tablero[0][5]+=5;
                F8.setIcon(new ImageIcon(this.getClass().getResource("ReyBlanco.svg.png")));
            }
        } else if (tablero[0][5] == 4) {
            tablero[0][5]=0;
            if (Caballo_n()) {
                F8.setIcon(new ImageIcon(this.getClass().getResource("CaballoNegro.svg.png")));
                tablero[0][5]+=4;
            }else{
                tablero[0][5]+=5;
                F8.setIcon(new ImageIcon(this.getClass().getResource("ReyBlanco.svg.png")));
            }
        } else if (tablero[0][5] == 5) {
            F8.setIcon(new ImageIcon(this.getClass().getResource("ReyBlanco.svg.png")));
        } else if (tablero[0][5] == 6) {
            F8.setIcon(new ImageIcon(this.getClass().getResource("ReyNegro.svg.png")));
        } else {
            F8.setIcon(null);
            tablero[0][5] = 0;
        }
        impr();
    }//GEN-LAST:event_F8MouseClicked

    private void G8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_G8MouseClicked
        // TODO add your handling code here:
        tablero[0][6]++;
        if (tablero[0][6] == 1) {
            if (Peon_b()) {
                G8.setIcon(new ImageIcon(this.getClass().getResource("PeonBlanco.svg.png")));
                tablero[0][6]++;
            }else if (!Caballo_b() && !Caballo_n()) {
                tablero[0][6] += 2;
                G8.setIcon(new ImageIcon(this.getClass().getResource("ReyBlanco.svg.png")));
            } 
        } else if (tablero[0][6] == 3) {
            tablero[0][6]=0;
            if (Caballo_b()) {
                G8.setIcon(new ImageIcon(this.getClass().getResource("CaballoBlanco.svg.png")));
                tablero[0][6]=3;
            } else if (Caballo_n()) {
                tablero[0][6]++;
                G8.setIcon(new ImageIcon(this.getClass().getResource("CaballoNegro.svg.png")));
                if(!Caballo_b()){
                    tablero[0][6]+=3;
                }
            }else if(!Caballo_n() && !Caballo_b()){
                tablero[0][6]+=5;
                G8.setIcon(new ImageIcon(this.getClass().getResource("ReyBlanco.svg.png")));
            }
        } else if (tablero[0][6] == 4) {
            tablero[0][6]=0;
            if (Caballo_n()) {
                G8.setIcon(new ImageIcon(this.getClass().getResource("CaballoNegro.svg.png")));
                tablero[0][6]+=4;
            }else{
                tablero[0][6]+=5;
                G8.setIcon(new ImageIcon(this.getClass().getResource("ReyBlanco.svg.png")));
            }
        } else if (tablero[0][6] == 5) {
            G8.setIcon(new ImageIcon(this.getClass().getResource("ReyBlanco.svg.png")));
        } else if (tablero[0][6] == 6) {
            G8.setIcon(new ImageIcon(this.getClass().getResource("ReyNegro.svg.png")));
        } else {
            G8.setIcon(null);
            tablero[0][6] = 0;
        }
        impr();
    }//GEN-LAST:event_G8MouseClicked

    private void H8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_H8MouseClicked
        // TODO add your handling code here:
        tablero[0][7]++;
        if (tablero[0][7] == 1) {
            if (Peon_b()) {
                H8.setIcon(new ImageIcon(this.getClass().getResource("PeonBlanco.svg.png")));
                tablero[0][7]++;
            }else if (!Caballo_b() && !Caballo_n()) {
                tablero[0][7] += 2;
                H8.setIcon(new ImageIcon(this.getClass().getResource("ReyBlanco.svg.png")));
            } 
        } else if (tablero[0][7] == 3) {
            tablero[0][7]=0;
            if (Caballo_b()) {
                H8.setIcon(new ImageIcon(this.getClass().getResource("CaballoBlanco.svg.png")));
                tablero[0][7]=3;
            } else if (Caballo_n()) {
                tablero[0][7]++;
                H8.setIcon(new ImageIcon(this.getClass().getResource("CaballoNegro.svg.png")));
                if(!Caballo_b()){
                    tablero[0][7]+=3;
                }
            }else if(!Caballo_n() && !Caballo_b()){
                tablero[0][7]+=5;
                H8.setIcon(new ImageIcon(this.getClass().getResource("ReyBlanco.svg.png")));
            }
        } else if (tablero[0][7] == 4) {
            tablero[0][7]=0;
            if (Caballo_n()) {
                H8.setIcon(new ImageIcon(this.getClass().getResource("CaballoNegro.svg.png")));
                tablero[0][7]+=4;
            }else{
                tablero[0][7]+=5;
                H8.setIcon(new ImageIcon(this.getClass().getResource("ReyBlanco.svg.png")));
            }
        } else if (tablero[0][7] == 5) {
            H8.setIcon(new ImageIcon(this.getClass().getResource("ReyBlanco.svg.png")));
        } else if (tablero[0][7] == 6) {
            H8.setIcon(new ImageIcon(this.getClass().getResource("ReyNegro.svg.png")));
        } else {
            H8.setIcon(null);
            tablero[0][7] = 0;
        }
        impr();
    }//GEN-LAST:event_H8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChessOracle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChessOracle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChessOracle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChessOracle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChessOracle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton A1;
    private javax.swing.JButton A2;
    private javax.swing.JButton A3;
    private javax.swing.JButton A4;
    private javax.swing.JButton A5;
    private javax.swing.JButton A6;
    private javax.swing.JButton A7;
    private javax.swing.JButton A8;
    private javax.swing.JButton B1;
    private javax.swing.JButton B2;
    private javax.swing.JButton B3;
    private javax.swing.JButton B4;
    private javax.swing.JButton B5;
    private javax.swing.JButton B6;
    private javax.swing.JButton B7;
    private javax.swing.JButton B8;
    private javax.swing.JButton C1;
    private javax.swing.JButton C2;
    private javax.swing.JButton C3;
    private javax.swing.JButton C4;
    private javax.swing.JButton C5;
    private javax.swing.JButton C6;
    private javax.swing.JButton C7;
    private javax.swing.JButton C8;
    private javax.swing.JButton D1;
    private javax.swing.JButton D2;
    private javax.swing.JButton D3;
    private javax.swing.JButton D4;
    private javax.swing.JButton D5;
    private javax.swing.JButton D6;
    private javax.swing.JButton D7;
    private javax.swing.JButton D8;
    private javax.swing.JButton E1;
    private javax.swing.JButton E2;
    private javax.swing.JButton E3;
    private javax.swing.JButton E4;
    private javax.swing.JButton E5;
    private javax.swing.JButton E6;
    private javax.swing.JButton E7;
    private javax.swing.JButton E8;
    private javax.swing.JButton F1;
    private javax.swing.JButton F2;
    private javax.swing.JButton F3;
    private javax.swing.JButton F4;
    private javax.swing.JButton F5;
    private javax.swing.JButton F6;
    private javax.swing.JButton F7;
    private javax.swing.JButton F8;
    private javax.swing.JButton G1;
    private javax.swing.JButton G2;
    private javax.swing.JButton G3;
    private javax.swing.JButton G4;
    private javax.swing.JButton G5;
    private javax.swing.JButton G6;
    private javax.swing.JButton G7;
    private javax.swing.JButton G8;
    private javax.swing.JButton H1;
    private javax.swing.JButton H2;
    private javax.swing.JButton H3;
    private javax.swing.JButton H4;
    private javax.swing.JButton H5;
    private javax.swing.JButton H6;
    private javax.swing.JButton H7;
    private javax.swing.JButton H8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
    int pieza_actual = 0;
    int tablero[][] = {{0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0}};
    
    public void impr(){
        for (int i = 0; i < tablero.length; i++) {
            for (int j = 0; j < tablero.length; j++) {
                System.out.print(tablero[i][j]);
            }
            System.out.println();
        }
        System.out.println();
    }
    
    public boolean Caballo_b() {
        int caballo_b = 0;
        for (int i = 0; i < tablero.length; i++) {
            for (int j = 0; j < tablero.length; j++) {
                if (tablero[i][j] == 3) {
                    caballo_b++;
                }
            }
        }
        if (caballo_b < 2) {
            return true;
        } else {
            return false;
        }
    }
    
    public boolean Caballo_n() {
        int caballo_n = 0;
        for (int i = 0; i < tablero.length; i++) {
            for (int j = 0; j < tablero.length; j++) {
                if (tablero[i][j] == 4) {
                    caballo_n++;
                }
            }
        }
        
        if (caballo_n < 2) {
            return true;
        } else {
            return false;
        }
    }
    
    public boolean Rey_b() {
        int Rey_b = 0;
        for (int i = 0; i < tablero.length; i++) {
            for (int j = 0; j < tablero.length; j++) {
                if (tablero[i][j] == 5) {
                    Rey_b++;
                }
            }
        }
        
        if (Rey_b < 2) {
            return true;
        } else {
            return false;
        }
    }
    
    public boolean Rey_n() {
        int Rey_n = 0;
        for (int i = 0; i < tablero.length; i++) {
            for (int j = 0; j < tablero.length; j++) {
                if (tablero[i][j] == 6) {
                    Rey_n++;
                }
            }
        }
        
        if (Rey_n < 2) {
            return true;
        } else {
            return false;
        }
    }
    
    public boolean Peon_b() {
        int Peon_b = 0;
        for (int i = 0; i < tablero.length; i++) {
            for (int j = 0; j < tablero.length; j++) {
                if (tablero[i][j] == 1) {
                    Peon_b++;
                }
            }
        }
        
        if (Peon_b < 9) {
            return true;
        } else {
            return false;
        }
    }
    
    public boolean Peon_n() {
        int Peon_n = 0;
        for (int i = 0; i < tablero.length; i++) {
            for (int j = 0; j < tablero.length; j++) {
                if (tablero[i][j] == 1) {
                    Peon_n++;
                }
            }
        }
        
        if (Peon_n < 9) {
            return true;
        } else {
            return false;
        }
    }
}
